apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: pod-myapp
  namespace: default
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080