apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}
spec:
  selector:
    {{- include "app-chart.selectorLabels" . | nindent 4 }}
  ports:        
    - name: multitool 
      protocol: TCP  
      port: {{ .Values.service.port }} 
      targetPort: {{ .Values.service.targetPort }} 
  type: {{ .Values.service.type }}