frontend:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    # tag: "1.21.0"  
  replicaCount: 1

  ingress:
    enable: true
    className: "nginx"     
    hosts:
      - host: qa-my-app.ru
        paths:
          - path: /
            pathType: Prefix
    tls: []

  service:
    type: ClusterIP
    port: 80
    targetPort: 80  

backend:
  image:
    repository: praqma/network-multitool
    tag: "latest"
    pullPolicy: "IfNotPresent"
  replicaCount: 1

  service:
    type: ClusterIP
    port: 9002
    targetPort: 80 