{{- if .Values.service.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: default
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
    - name: {{ .Values.service.name }}  
      protocol: TCP
      port: 80
      targetPort: 5000     
{{- end }}