apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
spec:
  selector:
    app: nginx-multitool 
  ports:
    - name: nginx  
      protocol: TCP
      port: 80
      targetPort: 80
      protocol: TCP
    - name: multitool   
      port: 81
      targetPort: 8080  