apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool
  namespace: default
  labels:
    app: busybox-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'while true; do sleep 5;  echo $(date) Success! > /output/success.txt; done;']
        volumeMounts:
        - name: vol
          mountPath: /output
      - name: multitool
        image: praqma/network-multitool:latest
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'while true; do  sleep 5;  cat /input/success.txt; done;']
        volumeMounts:
        - name: vol
          mountPath: /input        
      volumes:
      - name: vol    
        persistentVolumeClaim:
          claimName: pvc-vol
           