apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:  
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/data/pv1"