apiVersion: v1
kind: Pod
metadata:
  name: "mypod"
spec:
  containers:
  - name: nginx
    image: "nginx"       
    volumeMounts:
    - name: localtime
      mountPath: /dat
  - name: redis
    image: "redis"        
    volumeMounts:
    - name: localtime
      mountPath: /dbo      
  volumes:
  - name: localtime
    # emptyDir: {}
    hostPath:
      path: /var/data
    