apiVersion: v1
kind: Pod
metadata:
  name: "volume-pod"
spec:
  containers:
  - name: app1
    image: busybox    
    command: ['sh', '-c', 'while true; do sleep 5;  echo $(date) Success! > /output/success.txt; done;']    
    volumeMounts:
    - name: vol
      mountPath: /output
  volumes:
  - name: vol    
    hostPath:
      path: /var/data