apiVersion: apps/v1
kind: Deployment
metadata: 
  name: "api-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:                    
      containers:
      - name: api-conatsiner
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: api-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: api-html
        configMap:
          name: api-html      
---
apiVersion: v1
kind: ConfigMap              
metadata:
  name: api-html
data:
  key1: value1
  index.html: |
    <html>
    <body>
      <h1>api</h1>
    <body>
    <html>    
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api 
  ports:   
    - protocol: TCP  
      port: 80
      targetPort: 80
  type: ClusterIP    