apiVersion: v1
kind: Pod
metadata:
  name: "busybox-env-pod"
spec:
  containers:
  - name: busybox
    image: busybox    
    command: ['sh', '-c', 'env']
    env:
    - name: VAR1
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: VAR1
    - name: VAR2
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: VAR2  
    - name: VAR3
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: VAR3
    - name: SECRET_VAR1
      valueFrom:
        secretKeyRef:
          name: env-secret
          key: SECRET_VAR1

    - name: SECRET_VAR2
      valueFrom:
        secretKeyRef:
          name: env-secret
          key: SECRET_VAR2
  restartPolicy: Never      
   