apiVersion: v1
kind: Pod
metadata:
  name: "busybox-env-pod"
spec:
  containers:
  - name: busybox
    image: busybox    
    command: ['sh', '-c', 'env']
    envFrom:
    - configMapRef:
        name: env-config
    - secretRef:
        name: env-secret
  restartPolicy: Never      
   